export interface LGAInfo {
  id: string;
  name: string;
  senatorialDistrict: 'Uyo (North-East)' | 'Ikot Ekpene (North-West)' | 'Eket (South)';
  headquarters: string;
  notableLandmarks: string[];
  keyResources: string[];
  majorMarkets: string[];
  emergencyContact: string;
  description: string;
  populationEstimate: string;
  dialects: string[];
}

export const AKWA_IBOM_LGAS: LGAInfo[] = [
  // ── Uyo Senatorial District (9 LGAs) ───────────────────────────────────────
  {
    id: 'uyo',
    name: 'Uyo',
    senatorialDistrict: 'Uyo (North-East)',
    headquarters: 'Uyo Metropolis',
    notableLandmarks: ['Godswill Akpabio Int’l Stadium', 'Ibom Plaza', 'State Secretariat', 'Tropicana Mall', 'Ibom Hall'],
    keyResources: ['Commercial Trading', 'ICT Hubs', 'Hospitality', 'Real Estate'],
    majorMarkets: ['Akpan Andem Market', 'Itam Market', 'Plaza Night Market'],
    emergencyContact: '0803 112 0001',
    description: 'The capital city of Akwa Ibom State, a modern metropolis known for neat road networks, tree-lined boulevards, and booming digital/commercial activity.',
    populationEstimate: '550,000+',
    dialects: ['Ibibio'],
  },
  {
    id: 'itu',
    name: 'Itu',
    senatorialDistrict: 'Uyo (North-East)',
    headquarters: 'Mbak Atai',
    notableLandmarks: ['Mary Slessor Memorial Cairn', 'Itu Bridge / Ayadehe Waterway', 'Rubber Research Institute'],
    keyResources: ['Rubber', 'Palm Produce', 'Fishing', 'Sand Dredging'],
    majorMarkets: ['Urua Itam', 'Ayadehe Fish Market'],
    emergencyContact: '0803 112 0002',
    description: 'Historic gateway between Akwa Ibom and Cross River State, renowned for the pioneering missionary works of Mary Slessor and rubber plantations.',
    populationEstimate: '170,000+',
    dialects: ['Ibibio', 'Itu Mbon Uso'],
  },
  {
    id: 'ibiono-ibom',
    name: 'Ibiono Ibom',
    senatorialDistrict: 'Uyo (North-East)',
    headquarters: 'Oko Ita',
    notableLandmarks: ['Presbyterian Church of Nigeria (Historic Site)', 'Ididep Hills', 'Oko Ita Cultural Center'],
    keyResources: ['Palm Oil', 'Cassava', 'Cocoa', 'Timber'],
    majorMarkets: ['Urua Oko Ita', 'Urua Ididep'],
    emergencyContact: '0803 112 0003',
    description: 'One of the largest local government areas by landmass with deep historical religious heritage, fertile agrarian rolling hills, and palm cultivation.',
    populationEstimate: '260,000+',
    dialects: ['Ibibio'],
  },
  {
    id: 'uruan',
    name: 'Uruan',
    senatorialDistrict: 'Uyo (North-East)',
    headquarters: 'Idu',
    notableLandmarks: ['Ibom Icon Hotel & Golf Resort', 'Nwaniba Beach / Waterway', 'Le Meridien Marina'],
    keyResources: ['Freshwater Fish', 'Tourism', 'Palm Wine', 'Agriculture'],
    majorMarkets: ['Urua Nwaniba', 'Urua Idu'],
    emergencyContact: '0803 112 0004',
    description: 'Coastal eco-tourism powerhouse hosting the world-class Ibom Icon Golf Resort along the Nwaniba riverine belt.',
    populationEstimate: '150,000+',
    dialects: ['Ibibio'],
  },
  {
    id: 'ibesikpo-asutan',
    name: 'Ibesikpo Asutan',
    senatorialDistrict: 'Uyo (North-East)',
    headquarters: 'Nung Udoe',
    notableLandmarks: ['Nung Udoe Roundabout Market', 'Asutan Civic Center'],
    keyResources: ['Palm Oil', 'Cassava / Garri', 'Vegetables', 'Pottery'],
    majorMarkets: ['Urua Nung Udoe (Famous 8-day Market)', 'Afaha Market'],
    emergencyContact: '0803 112 0005',
    description: 'Bordering Uyo capital, famous for the bustling Nung Udoe market hub and intensive agro-processing.',
    populationEstimate: '180,000+',
    dialects: ['Ibibio'],
  },
  {
    id: 'nsit-ibom',
    name: 'Nsit Ibom',
    senatorialDistrict: 'Uyo (North-East)',
    headquarters: 'Afaha Offiong',
    notableLandmarks: ['Afaha Offiong Civic Grounds', 'Edebom Cultural Arena'],
    keyResources: ['Palm Oil', 'Yam', 'Plantain', 'Sand / Gravel'],
    majorMarkets: ['Urua Afaha Offiong', 'Urua Edebom'],
    emergencyContact: '0803 112 0006',
    description: 'Serene agrarian council known for high-grade palm oil extraction and rich cultural displays.',
    populationEstimate: '140,000+',
    dialects: ['Ibibio'],
  },
  {
    id: 'nsit-ubium',
    name: 'Nsit Ubium',
    senatorialDistrict: 'Uyo (North-East)',
    headquarters: 'Ikabara',
    notableLandmarks: ['Governor Umo Eno Country Estate', 'Ubium River Valley'],
    keyResources: ['Palm Produce', 'Cassava', 'Vegetables', 'Gravel'],
    majorMarkets: ['Urua Ikot Edibon', 'Urua Ndiya'],
    emergencyContact: '0803 112 0007',
    description: 'Homeland of the current Executive Governor of Akwa Ibom State, featuring scenic landscapes and agricultural production.',
    populationEstimate: '160,000+',
    dialects: ['Ibibio'],
  },
  {
    id: 'nsit-atai',
    name: 'Nsit Atai',
    senatorialDistrict: 'Uyo (North-East)',
    headquarters: 'Odot',
    notableLandmarks: ['Victor Attah Int’l Airport (Corridor)', 'Odot Civic Center'],
    keyResources: ['Aviation Logistics Corridor', 'Cassava', 'Poultry'],
    majorMarkets: ['Urua Odot', 'Urua Ikot Asua'],
    emergencyContact: '0803 112 0008',
    description: 'Fast-developing aviation economic zone surrounding the airport corridor with booming logistics opportunities.',
    populationEstimate: '110,000+',
    dialects: ['Ibibio'],
  },
  {
    id: 'etinan',
    name: 'Etinan',
    senatorialDistrict: 'Uyo (North-East)',
    headquarters: 'Etinan Town',
    notableLandmarks: ['Etinan General Hospital', 'Qua Iboe Church Cradle (Historic Chapel)', 'Etinan Institute'],
    keyResources: ['Palm Produce', 'Handicrafts', 'Education Institutions', 'Metal Fabrication'],
    majorMarkets: ['Urua Etinan', 'Urua Ekpene Ukpa'],
    emergencyContact: '0803 112 0009',
    description: 'Historic educational and religious cradle where early industrial craft schools and Qua Iboe missionary centers were first established.',
    populationEstimate: '210,000+',
    dialects: ['Ibibio'],
  },

  // ── Ikot Ekpene Senatorial District (10 LGAs) ──────────────────────────────
  {
    id: 'ikot-ekpene',
    name: 'Ikot Ekpene',
    senatorialDistrict: 'Ikot Ekpene (North-West)',
    headquarters: 'Ikot Ekpene Town (The Raffia City)',
    notableLandmarks: ['Raffia City Plaza & Craft Center', 'Four Points by Sheraton Hotel', 'Ikot Ekpene Prison Heritage', 'Federal Polytechnic'],
    keyResources: ['Raffia Crafts & Weaving', 'Wood Carving', 'Cane Works', 'Hospitality', 'Palm Oil'],
    majorMarkets: ['Urua Anwa', 'Raffia Craft Market'],
    emergencyContact: '0803 112 0010',
    description: 'Internationally celebrated as "The Raffia City", famous for intricate cane weaving, wood sculptures, and hospitality.',
    populationEstimate: '320,000+',
    dialects: ['Annang'],
  },
  {
    id: 'abak',
    name: 'Abak',
    senatorialDistrict: 'Ikot Ekpene (North-West)',
    headquarters: 'Abak Urban',
    notableLandmarks: ['Federal Government College Ikot Ekpene Road', 'Abak River Basin', 'Nigerian Army Barracks (Ibagwa)'],
    keyResources: ['Palm Oil Mills', 'Cassava Starch', 'Commercial Transport Hub'],
    majorMarkets: ['Urua Abak', 'Midim Market'],
    emergencyContact: '0803 112 0011',
    description: 'Strategic junction town connecting the commercial nerve centers of Annangland with Uyo and Port Harcourt.',
    populationEstimate: '200,000+',
    dialects: ['Annang'],
  },
  {
    id: 'essien-udim',
    name: 'Essien Udim',
    senatorialDistrict: 'Ikot Ekpene (North-West)',
    headquarters: 'Afaha Ikot Ebak',
    notableLandmarks: ['Ritman University Corridor', 'Topfaith University', 'Senate President Godswill Akpabio Residence (Ukana)'],
    keyResources: ['Tertiary Education', 'Palm Oil', 'Yam', 'Rice Cultivation'],
    majorMarkets: ['Urua Ukana', 'Urua Ikpe Annang'],
    emergencyContact: '0803 112 0012',
    description: 'Educational and political heavyweight LGA hosting top-tier universities, modern infrastructure, and rich agricultural outputs.',
    populationEstimate: '240,000+',
    dialects: ['Annang'],
  },
  {
    id: 'obot-akara',
    name: 'Obot Akara',
    senatorialDistrict: 'Ikot Ekpene (North-West)',
    headquarters: 'Nto Edino',
    notableLandmarks: ['Nto Edino - Ekwereazu Bridge (Abia Link)', 'Obot Akara Forest Reserve'],
    keyResources: ['Cocoa', 'Palm Oil', 'Cassava', 'Inter-State Border Commerce'],
    majorMarkets: ['Urua Nto Edino', 'Urua Nto Ndang'],
    emergencyContact: '0803 112 0013',
    description: 'Border gateway to Abia State with extensive interstate trade routes, cocoa plantations, and cassava processing.',
    populationEstimate: '190,000+',
    dialects: ['Annang'],
  },
  {
    id: 'ika',
    name: 'Ika',
    senatorialDistrict: 'Ikot Ekpene (North-West)',
    headquarters: 'Urua Inyang',
    notableLandmarks: ['Urua Inyang Council Headquarters', 'Achan Ika Cultural Center'],
    keyResources: ['Palm Oil', 'Timber', 'Plantain', 'Hunting'],
    majorMarkets: ['Urua Inyang', 'Ito Market'],
    emergencyContact: '0803 112 0014',
    description: 'Rich agricultural council bordered by Rivers State, renowned for vast palm estates and forest products.',
    populationEstimate: '120,000+',
    dialects: ['Annang'],
  },
  {
    id: 'ukanafun',
    name: 'Ukanafun',
    senatorialDistrict: 'Ikot Ekpene (North-West)',
    headquarters: 'Ikot Akpa Nkuk',
    notableLandmarks: ['Ikot Akpa Nkuk Civic Hall', 'Ukanafun Palm Valley'],
    keyResources: ['Palm Oil Production', 'Garri Processing', 'Rubber'],
    majorMarkets: ['Urua Ikot Akpa Nkuk', 'Urua Obonukpa'],
    emergencyContact: '0803 112 0015',
    description: 'Agricultural hub with dense high-yield palm oil production and community farming cooperatives.',
    populationEstimate: '175,000+',
    dialects: ['Annang'],
  },
  {
    id: 'oruk-anam',
    name: 'Oruk Anam',
    senatorialDistrict: 'Ikot Ekpene (North-West)',
    headquarters: 'Ikot Ibritam',
    notableLandmarks: ['Ikot Ibritam Palm Belt', 'Inen Cultural Arena'],
    keyResources: ['Palm Oil', 'Cassava', 'Timber', 'Clay Deposit'],
    majorMarkets: ['Urua Ikot Ibritam', 'Urua Inen'],
    emergencyContact: '0803 112 0016',
    description: 'One of the largest landmass councils in the state with vast fertile agrarian expanse and cottage palm oil processing.',
    populationEstimate: '230,000+',
    dialects: ['Annang'],
  },
  {
    id: 'ikono',
    name: 'Ikono',
    senatorialDistrict: 'Ikot Ekpene (North-West)',
    headquarters: 'Ibiaku Ntok Okpo',
    notableLandmarks: ['The Cradle of the Ibibio Nation', 'Ibiaku Ntok Okpo Agricultural Zone'],
    keyResources: ['Oil Palm', 'Yam', 'Plantain', 'Historic Heritage'],
    majorMarkets: ['Urua Ibiaku Ntok Okpo', 'Urua Ediene'],
    emergencyContact: '0803 112 0017',
    description: 'Revered as the historical "Cradle of the Ibibio Nation" from where early ancestors dispersed across the state.',
    populationEstimate: '180,000+',
    dialects: ['Ibibio'],
  },
  {
    id: 'ini',
    name: 'Ini',
    senatorialDistrict: 'Ikot Ekpene (North-West)',
    headquarters: 'Odoro Ikpe',
    notableLandmarks: ['Ini Rice Farms / Processing Mills', 'Odoro Ikpe Hills', 'Usuk Ukwam Rubber Estate'],
    keyResources: ['Rice Cultivation (Food Basket)', 'Cocoa', 'Cassava', 'Solid Minerals'],
    majorMarkets: ['Urua Odoro Ikpe', 'Urua Ikpe Ikot Nkon'],
    emergencyContact: '0803 112 0018',
    description: 'The "Food Basket of Akwa Ibom State", celebrated for large-scale swamp and upland rice production, cocoa, and hilly beauty.',
    populationEstimate: '130,000+',
    dialects: ['Ibibio', 'Enyong'],
  },

  // ── Eket Senatorial District (12 LGAs) ─────────────────────────────────────
  {
    id: 'eket',
    name: 'Eket',
    senatorialDistrict: 'Eket (South)',
    headquarters: 'Eket Urban',
    notableLandmarks: ['Mobil / ExxonMobil Production Complex (QIT Corridor)', 'Eket Sports Stadium', 'Grace Bill Avenue Commercial Strip'],
    keyResources: ['Crude Oil Logistics', 'Natural Gas', 'Marine Services', 'Hospitality'],
    majorMarkets: ['Urua Kpokpo (Eket Main Market)', 'Udua Market'],
    emergencyContact: '0803 112 0019',
    description: 'The industrial oil hub of Akwa Ibom State, home to major multinational petroleum operations, urban centers, and lively commerce.',
    populationEstimate: '290,000+',
    dialects: ['Ekid (Eket)', 'Ibibio'],
  },
  {
    id: 'ibeno',
    name: 'Ibeno',
    senatorialDistrict: 'Eket (South)',
    headquarters: 'Ukpenekang',
    notableLandmarks: ['Ibeno Beach (Longest Sand Beach in West Africa - 30km+)', 'Mobil Qua Iboe Terminal (QIT)', 'Ibeno Mangrove Forest'],
    keyResources: ['Crude Oil & Gas', 'Deep Sea Fishing', 'Seafood / Prawns', 'Eco-Tourism'],
    majorMarkets: ['Urua Ukpenekang Fish Market', 'Ibeno Beach Landing Jetty'],
    emergencyContact: '0803 112 0020',
    description: 'Coastal paradise featuring West Africa’s longest continuous natural sand beach, major offshore crude export terminals, and rich marine harvest.',
    populationEstimate: '115,000+',
    dialects: ['Ibeno', 'Ibibio'],
  },
  {
    id: 'onna',
    name: 'Onna',
    senatorialDistrict: 'Eket (South)',
    headquarters: 'Abat',
    notableLandmarks: ['Kings Flour Mill', 'Jubilee Syringe Manufacturing Company', 'Lion Plywood Factory', 'Former Gov. Udom Emmanuel Country Home'],
    keyResources: ['Manufacturing Industries', 'Cassava Starch', 'Palm Oil', 'Crude Oil Corridor'],
    majorMarkets: ['Urua Abat', 'Urua Ndon Eyo'],
    emergencyContact: '0803 112 0021',
    description: 'Modern industrial center hosting multiple high-tech manufacturing factories and agricultural processing estates.',
    populationEstimate: '165,000+',
    dialects: ['Ibibio'],
  },
  {
    id: 'esit-eket',
    name: 'Esit Eket',
    senatorialDistrict: 'Eket (South)',
    headquarters: 'Uquo',
    notableLandmarks: ['Akwa Palms Oil Estate', 'Uquo Civic Square'],
    keyResources: ['Palm Oil Plantation', 'Crude Oil', 'Cassava', 'Timber'],
    majorMarkets: ['Urua Uquo', 'Urua Etebi'],
    emergencyContact: '0803 112 0022',
    description: 'Home to the expansive Akwa Palms agro-industrial estate and rich coastal plain agriculture.',
    populationEstimate: '95,000+',
    dialects: ['Ekid (Eket)'],
  },
  {
    id: 'oron',
    name: 'Oron',
    senatorialDistrict: 'Eket (South)',
    headquarters: 'Oron Beach Urban',
    notableLandmarks: ['National Museum of Colonial History Oron', 'Maritime Academy of Nigeria (MAN)', 'Oron Beach Jetty & Ferry Landing'],
    keyResources: ['Seafood & Crayfish Export', 'Marine Logistics & Transport', 'Maritime Training', 'Fish Smoking'],
    majorMarkets: ['Oron Beach Crayfish Market', 'Urua Ntak Inyang'],
    emergencyContact: '0803 112 0023',
    description: 'Premier national seafood and crayfish hub, maritime training headquarters of Nigeria, and waterway bridge to Calabar and Cameroon.',
    populationEstimate: '220,000+',
    dialects: ['Oro (Oron)'],
  },
  {
    id: 'mbo',
    name: 'Mbo',
    senatorialDistrict: 'Eket (South)',
    headquarters: 'Enwang',
    notableLandmarks: ['Ibom Deep Seaport & Free Trade Zone Site', 'Ibaka Deep Sea Anchorage', 'Enwang Bridge'],
    keyResources: ['Deep Sea Maritime Port', 'Oil & Gas', 'Artisanal & Deepwater Fisheries'],
    majorMarkets: ['Urua Ibaka Fish Market', 'Urua Enwang'],
    emergencyContact: '0803 112 0024',
    description: 'Strategic coastal peninsula hosting the upcoming Ibom Deep Seaport and Nigeria’s premier deepwater naval and commercial anchorage.',
    populationEstimate: '140,000+',
    dialects: ['Oro (Oron)', 'Ebughu'],
  },
  {
    id: 'urue-offong-oruko',
    name: 'Urue-Offong/Oruko',
    senatorialDistrict: 'Eket (South)',
    headquarters: 'Urue Offong',
    notableLandmarks: ['Urue Offong Agro Junction', 'Oruko Civic Hall'],
    keyResources: ['Palm Oil', 'Cassava', 'Plantain', 'Timber'],
    majorMarkets: ['Urua Offong Market', 'Urua Oruko'],
    emergencyContact: '0803 112 0025',
    description: 'Heart of the Oro nation agricultural belt, connecting Oron urban with inner farming communities.',
    populationEstimate: '105,000+',
    dialects: ['Oro (Oron)'],
  },
  {
    id: 'okobo',
    name: 'Okobo',
    senatorialDistrict: 'Eket (South)',
    headquarters: 'Okopedi',
    notableLandmarks: ['Okopedi Junction Market', 'Okobo Mangrove Estuary'],
    keyResources: ['Cassava', 'Palm Produce', 'Fish', 'Clay & Sand'],
    majorMarkets: ['Urua Okopedi', 'Urua Amamong'],
    emergencyContact: '0803 112 0026',
    description: 'Scenic riverine and farm council linking Uyo directly to the Oron coastal belt.',
    populationEstimate: '135,000+',
    dialects: ['Okobo', 'Oro'],
  },
  {
    id: 'udung-uko',
    name: 'Udung Uko',
    senatorialDistrict: 'Eket (South)',
    headquarters: 'Eyofin',
    notableLandmarks: ['Eyofin Waterfront Jetty', 'Udung Uko Cultural Center'],
    keyResources: ['Seafood', 'Palm Oil', 'Cassava', 'River Transport'],
    majorMarkets: ['Urua Eyofin', 'Urua Udung Uko'],
    emergencyContact: '0803 112 0027',
    description: 'Compact riverine council celebrated for close-knit fishing communities and water transport routes.',
    populationEstimate: '75,000+',
    dialects: ['Oro (Oron)'],
  },
  {
    id: 'ikot-abasi',
    name: 'Ikot Abasi',
    senatorialDistrict: 'Eket (South)',
    headquarters: 'Ikot Abasi Town (Opobo Channel)',
    notableLandmarks: ['1914 Amalgamation House (Lord Lugard)', 'Bridge of No Return & Slave Depot', 'ALSCON Smelter Plant', 'Ibom Power Plant (IPC)'],
    keyResources: ['Ibom Power Generation (191MW)', 'Natural Gas', 'Aluminum Smelting', 'Historical Tourism', 'Fishing'],
    majorMarkets: ['Urua Ikot Abasi', 'Urua Egbo Ibi'],
    emergencyContact: '0803 112 0028',
    description: 'Monumental historic town where Nigeria’s 1914 amalgamation papers were signed; host of Ibom Power Company thermal plant and ALSCON.',
    populationEstimate: '185,000+',
    dialects: ['Ibibio'],
  },
  {
    id: 'mkpat-enin',
    name: 'Mkpat Enin',
    senatorialDistrict: 'Eket (South)',
    headquarters: 'Mkpat Enin Town',
    notableLandmarks: ['Akwa Ibom State University (AKSU Main Campus, Ikot Akpaden)', 'Coconut Oil Refinery Estate'],
    keyResources: ['Tertiary Education', 'Coconut Plantation & Processing', 'Palm Oil', 'Cassava'],
    majorMarkets: ['Urua Mkpat Enin', 'Urua Ikot Akpaden'],
    emergencyContact: '0803 112 0029',
    description: 'Education and agro-industrial center hosting the main university campus of AKSU and state coconut refining estate.',
    populationEstimate: '235,000+',
    dialects: ['Ibibio'],
  },
  {
    id: 'eastern-obolo',
    name: 'Eastern Obolo',
    senatorialDistrict: 'Eket (South)',
    headquarters: 'Okoroete',
    notableLandmarks: ['Okoroete Beachfront', 'Eastern Obolo Estuary Sanctuary', 'Offshore Oil Fields'],
    keyResources: ['Offshore Crude Oil', 'Deepwater Marine Fisheries', 'Crayfish', 'Mangrove Forest'],
    majorMarkets: ['Urua Okoroete Fish Market', 'Elile Landing Jetty'],
    emergencyContact: '0803 112 0030',
    description: 'Pristine coastal delta council with vast marine life, offshore oil production fields, and rich seafood culture.',
    populationEstimate: '85,000+',
    dialects: ['Obolo (Andoni)'],
  },
];
